FROM golang:1.13

LABEL maintainer="siddharth.rawat1001@gmail.com"

WORKDIR /mygoapp

COPY go.mod go.mod
COPY go.sum go.sum

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .
